version: "3.1"
services:
    backend:
        container_name: backend_node
        build: ./
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        links:
            - mongo
    mongo:
        image: mongo
        volumes: 
            - ./mongo-volume:/data/db
        ports:
            - "27017:27017"